[io]
# Fast profile keeps overwriting enabled so reprocessing replaces outputs.
overwrite_existing = true

[clean]
# Disable full metadata sanitisation for quicker turnaround.
sanitize_metadata = false
# Leave hidden text threshold at the baseline inherited setting.
hidden_text_alpha_threshold = 0

[passwords]
# Still honour per-directory password hints when present.
hint_filename = "passwords.txt"

[[watermarks.rules]]
# Adjust watermark heuristics to catch larger footer notices in speed runs.
name = "order_reference"
pattern = ".+\\(Order #\\d+\\)$"
max_font_size = 16.0
max_distance_from_bottom = 160.0
fonts = ["helv", "helvetica", "helvetica-bold"]
