[io]
# Directory used to mirror cleaned PDFs. Relative paths resolve from the process working directory.
output_dir = "_processed"
# When true (default) existing files are overwritten; set to false to keep prior runs untouched.
overwrite_existing = true
# Skip writing outputs when no mutations occur (still mirrors missing files on first run).
skip_unchanged = false

  [io.run_log]
  # Persist a summary of each run to an NDJSON file.
  enabled = false
  # Optional custom run log path. When blank, defaults to "<output_dir>/run_log.ndjson".
  path = ""
  # Suppress success messages when run logs are written.
  quiet = false

[clean]
# Backwards-compatible alias controlling both document and image metadata stripping.
sanitize_metadata = true
# Remove Info/XMP metadata from the document when true.
strip_document_metadata = true
# Remove embedded image metadata when true.
strip_image_metadata = true
# Remove hidden text spans (opacity <= threshold) when true.
remove_hidden_text = true
# Hidden text spans with opacity <= threshold are removed. Increase to catch semi-transparent overlays.
hidden_text_alpha_threshold = 0
# Collect page text for each processed PDF.
extract_text = true

[passwords]
# Fallback password applied when no explicit mapping or hint matches (empty string disables the fallback).
default = ""
# Per-directory password hint filename. Blank or missing value disables hint lookups.
hint_filename = "passwords.txt"
# Optional global password mapping file path. Empty string keeps the feature disabled by default.
password_file = ""

[watermarks]
# Toggle watermark detection/removal.
enabled = true
# Limit detection to the bottom N millimetres of each page (0 = full page).
clip_bottom_mm = 0.0
# Stop scanning a page after the first rule matches.
stop_after_first = false
# Only scan the first/last N pages for watermarks (0 = all pages).
max_pages = 0

[[watermarks.rules]]
# Rule targeting per-order download notices near the footer.
name = "order_reference"
pattern = ".+\\(Order #\\d+\\)$"
max_font_size = 14.0
max_distance_from_bottom = 140.0
fonts = ["helv", "helvetica", "helvetica-bold"]

[[watermarks.rules]]
# Rule targeting the standard DriveThruRPG "Downloaded by ..." footer line.
name = "download_notice"
pattern = "^Downloaded by\\s+.+?\\s+on\\s+.+?\\.\\s*Unauthorized distribution prohibited\\.?$"
ignore_case = true
max_font_size = 14.0
max_distance_from_bottom = 140.0
fonts = ["helv", "helvetica", "helvetica-bold"]

[performance]
# Number of worker processes for per-file parallelism ("auto" uses CPU count).
processes = "auto"
# How many tasks to dispatch per chunk when scheduling workers.
batch_size = 8

[save]
# Optimise saved PDFs for web view (Acrobat 10 compatibility).
linearize = false
# MuPDF garbage collection level (0-4) when saving.
garbage = 4
# Compress object streams during save.
deflate = true
