[io]
# Directory used to mirror cleaned PDFs. Relative paths resolve from the process working directory.
output_dir = "_processed"
# When true (default) existing files are overwritten; set to false to keep prior runs untouched.
overwrite_existing = false
# Skip writing outputs when no mutations occur.
skip_unchanged = true

  [io.run_log]
  # Persist a summary of each run to an NDJSON file.
  enabled = true
  # Custom run log path relative to the working directory.
  path = "_processed/run_log.ndjson"
  # Suppress success messages when run logs are written.
  quiet = false

[clean]
# Remove PDF Info/XMP metadata.
strip_document_metadata = true
# Remove embedded image metadata.
strip_image_metadata = true
# Remove hidden text spans (opacity <= threshold).
remove_hidden_text = true
# Hidden text spans with opacity <= threshold are removed.
hidden_text_alpha_threshold = 16
# Collect page text during processing.
extract_text = true

[passwords]
# Fallback password applied when no explicit mapping or hint matches (empty string disables the fallback).
default = ""
# Per-directory password hint filename. Blank or missing value disables hint lookups.
hint_filename = ""
# Optional global password mapping file path.
password_file = ""

[watermarks]
# Toggle watermark detection/removal.
enabled = true
# Only analyse the bottom N millimetres of each page.
clip_bottom_mm = 12.0
# Stop after the first match per page.
stop_after_first = true
# Scan the first/last N pages for watermarks (0 = all pages).
max_pages = 2

[[watermarks.rules]]
name = "download_notice"
pattern = "^Downloaded by\\s+.+?\\s+on\\s+.+?\\.\\s*Unauthorized distribution prohibited\\.?$"
ignore_case = true
max_font_size = 14.0
max_distance_from_bottom = 140.0
fonts = ["helv", "helvetica", "helvetica-bold"]

[[watermarks.rules]]
name = "order_reference"
pattern = ".+\\(Order #\\d+\\)$"
max_font_size = 14.0
max_distance_from_bottom = 140.0
fonts = ["helv", "helvetica", "helvetica-bold"]

[performance]
# Use half the available cores for parallel processing.
processes = 4
# Dispatch four files per batch to each worker.
batch_size = 4

[save]
# Optimise for Acrobat 10 without linearisation.
linearize = false
# MuPDF garbage collection level (0-4).
garbage = 4
# Compress object streams when saving.
deflate = true
